meta_product_name: "Tabata"
meta_title: "Conectando a los mejores productores industriales de México con los principales clientes de EE.UU. y México"
# meta_description: "Relevant description"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
